apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: kube-health
  # This ConfigMap tells the Prometheus Adapter how to discover metrics
  # and map them into Kubernetes custom metrics.
data:
  config.yaml: |
    rules:
    # We query Prometheus for 'pg_stat_activity_count', which we exported
    - seriesQuery: 'pg_stat_activity_count{namespace!="",pod!=""}'
      resources:
        # We rewrite the Prometheus labels into Kubernetes resource types
        # so Kubernetes knows which pod the metric belongs to.
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        # Match the native Prometheus name...
        matches: "pg_stat_activity_count"
        # ... and rename it to 'hospital_active_connections' for the K8s API.
        as: "hospital_active_connections"
      # The adapter will use this PromQL query when Kubernetes asks for the metric.
      metricsQuery: 'sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)'
